CREATE DATABASE IF NOT EXISTS ebby_digital;

USE ebby_digital;

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
fullname VARCHAR(100) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE projects (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT,
project_name VARCHAR(200),
service_type VARCHAR(100),
description TEXT,
status VARCHAR(50) DEFAULT 'Pending',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE quotes (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT,
service VARCHAR(100),
amount DECIMAL(10,2),
status VARCHAR(50) DEFAULT 'Pending',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoices (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT,
invoice_number VARCHAR(50),
amount DECIMAL(10,2),
status VARCHAR(50) DEFAULT 'Pending',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE uploads (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT,
file_name VARCHAR(255),
file_path VARCHAR(255),
uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
